// ─── TOTAL COST ───────────────────────────────────────────────────────────────
Total Cost = SUM ( CostExports[costInBillingCurrency] )

// ─── TIME INTELLIGENCE ────────────────────────────────────────────────────────
Cost MTD =
VAR _LastDate = MAX ( DateTable[Date] )
VAR _FirstOfMonth = DATE ( YEAR ( _LastDate ), MONTH ( _LastDate ), 1 )
RETURN
CALCULATE ( [Total Cost], DATESBETWEEN ( DateTable[Date], _FirstOfMonth, _LastDate ) )

Cost QTD = CALCULATE ( [Total Cost], DATESQTD ( DateTable[Date] ) )

Cost YTD = CALCULATE ( [Total Cost], DATESYTD ( DateTable[Date] ) )

// ─── PRIOR PERIOD ─────────────────────────────────────────────────────────────
Cost Prior Month =
VAR _MaxDate = MAX ( DateTable[Date] )
VAR _CurrentMonth = MONTH ( _MaxDate )
VAR _CurrentYear = YEAR ( _MaxDate )
VAR _PriorMonth = IF ( _CurrentMonth = 1, 12, _CurrentMonth - 1 )
VAR _PriorYear = IF ( _CurrentMonth = 1, _CurrentYear - 1, _CurrentYear )
RETURN
CALCULATE (
    [Total Cost],
    FILTER (
        ALL ( DateTable ),
        MONTH ( DateTable[Date] ) = _PriorMonth
        && YEAR ( DateTable[Date] ) = _PriorYear
    )
)

Cost Prior Year = CALCULATE ( [Total Cost], SAMEPERIODLASTYEAR ( DateTable[Date] ) )

// ─── MOM VARIANCE ─────────────────────────────────────────────────────────────
Cost MoM Change = [Total Cost] - [Cost Prior Month]

Cost MoM % =
IF (
    ISBLANK ( [Cost Prior Month] ) || [Cost Prior Month] = 0,
    BLANK (),
    DIVIDE ( [Cost MoM Change], [Cost Prior Month] )
)

Cost YoY % =
IF (
    ISBLANK ( [Cost Prior Year] ) || [Cost Prior Year] = 0,
    BLANK (),
    DIVIDE ( [Total Cost] - [Cost Prior Year], [Cost Prior Year] )
)

// ─── AVERAGES & FORECAST ──────────────────────────────────────────────────────
Avg Daily Cost = AVERAGEX ( VALUES ( DateTable[Date] ), CALCULATE ( [Total Cost] ) )

Avg Monthly Cost = AVERAGEX ( VALUES ( DateTable[MonthYear] ), CALCULATE ( [Total Cost] ) )

Cost Month Forecast =
VAR _Days = DAY ( EOMONTH ( TODAY (), 0 ) )
VAR _Day = DAY ( TODAY () )
RETURN IF ( _Day > 0, DIVIDE ( [Cost MTD], _Day ) * _Days )

Rolling 3M Avg = AVERAGEX (
    DATESINPERIOD ( DateTable[Date], LASTDATE ( DateTable[Date] ), -3, MONTH ),
    CALCULATE ( [Total Cost] )
)

// ─── DISPLAY & CURRENCY ───────────────────────────────────────────────────────
Total Cost DKK = "kr. " & FORMAT ( [Total Cost], "#,##0.00" )

Total Cost USD = SUMX ( CostExports, VALUE ( IF ( [costInUsd] = "", "0", [costInUsd] ) ) )

Avg Exchange Rate = AVERAGE ( CostExports[exchangeRatePricingToBilling] )

// ─── SHARE & BUDGET ───────────────────────────────────────────────────────────
Top N Cost Share % = DIVIDE ( [Total Cost], CALCULATE ( [Total Cost], ALL ( CostExports ) ) )

Budget = 1000  // ← replace with your monthly DKK target

Budget Variance = [Total Cost] - [Budget]

Budget Variance % = DIVIDE ( [Budget Variance], [Budget] )
